# Generated by Django 5.1.5 on 2025-02-07 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=150)),
                ('message', models.CharField(max_length=200)),
                ('group_name', models.CharField(max_length=20)),
            ],
        ),
    ]
